### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] after launching "mixt watch" on Windows

### ISSUE THREAD

**Issue by alexandrobin** [jvdsande/mixt#1]
Got the following issue after launching "mixt watch" on Windows : 

`$ mixt watch
(node:18356) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined`

Env : 
Windows 10
npm 6.5.0
node 11.9.0

**Comment by jvdsande** [comment]
Hi @alexandrobin 
Thanks for reporting!

Will look into int as soon as possible.

**Comment by jvdsande** [comment]
Hi @alexandrobin,

Sorry for the long wait.
Version 1.2.0 of Mixt should fix behavior on Windows machine.

Since I don't use Windows on a daily basis I was not able yet to test it thoroughly. Don't hesitate to update this issue if any cross-platform error occurs using 1.2.0

**Comment by jvdsande** [comment]
Closed for inactivity
